add LICENSE and README

diff --git a/.github/workflows/organisation-standards-validation.yml b/.github/workflows/organisation-standards-validation.yml
--- a/.github/workflows/organisation-standards-validation.yml
+++ b/.github/workflows/organisation-standards-validation.yml
@@ -65,6 +65,26 @@ jobs:
       if: always()
       shell: bash
 
+    - name: Check for README.md
+      run: |
+        FILE="README.md"
+        if [[ ! -f "$FILE" ]]; then
+          echo "Error: '$FILE' does not exist in the repository, please create one." >&2
+          exit 1
+        fi
+      if: always()
+      shell: bash
+
+    - name: Check for LICENSE file
+      run: |
+        FILE="LICENSE"
+        if [[ ! -f "$FILE" ]]; then
+          echo "Error: '$FILE' does not exist in the repository, please create one." >&2
+          exit 1
+        fi
+      if: always()
+      shell: bash
+
     - name: Check for test_documentation.md
       run: |
         FILE="test_documentation.md"
