changed message

diff --git a/.github/workflows/organisation-standards-validation.yml b/.github/workflows/organisation-standards-validation.yml
--- a/.github/workflows/organisation-standards-validation.yml
+++ b/.github/workflows/organisation-standards-validation.yml
@@ -69,7 +69,7 @@ jobs:
       run: |
         FILE="test_documentation.md"
         if [[ ! -f "$FILE" ]]; then
-          echo "Error: '$FILE' does not exist in the repository!" >&2
+          echo "Error: '$FILE' does not exist in the repository, please create one." >&2
           exit 1
         fi
       if: always()
@@ -79,7 +79,7 @@ jobs:
       run: |
         FILE="manual_testing_plan.md"
         if [[ ! -f "$FILE" ]]; then
-          echo "Error: '$FILE' does not exist in the repository!" >&2
+          echo "Error: '$FILE' does not exist in the repository, please create one." >&2
           exit 1
         fi
       if: always()
@@ -89,7 +89,7 @@ jobs:
       run: |
         FILE="setup_and_installation_guide.md"
         if [[ ! -f "$FILE" ]]; then
-          echo "Error: '$FILE' does not exist in the repository!" >&2
+          echo "Error: '$FILE' does not exist in the repository, please create one." >&2
           exit 1
         fi
       if: always()
